version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:latest
    ports:
      - "6380:6380"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"