name: Test Environment

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: sudo apt-get -y install docker-compose

    - name: Build and Start Docker Containers
      run: docker-compose up -d --build

    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to be ready..."
        sleep 15

    - name: Make test script executable
      run: chmod +x test.sh

    - name: Run test script
      run: ./test.sh

    - name: Shutdown Docker Compose
      run: docker-compose down